exclude: ['node_modules']
name: libtemplate
name_base: libtemplate
description: Template for JS libraries designed to work with GitHub Pages and Jekyll
nick: bebraw
author: Juho Vepsalainen
license: MIT
version: 0.2.4
jquery: ''
