exclude: ['node_modules', '_meta', 'scripts', 'npm-debug.log', 'README.md', 'Gruntfile.js', 'package.json', 'component.json']
name: libtemplate
name_base: libtemplate
description: Template for JS libraries designed to work with GitHub Pages and Jekyll
nick: bebraw
author: Juho Vepsalainen
license: MIT
version: 0.3.0
jquery: ''
