exclude: ['node_modules', '_meta', 'scripts', 'npm-debug.log', 'README.md', 'Gruntfile.js', 'package.json', 'component.json']
name: {{ name }}
name_base: {{ name_base }}
description: {{ description }}
nick: bebraw
author: {{ author }}
license: {{ license }}
version: {{ version }}
jquery: ''
